version: '3.7'
services:
  web:
    build:
      context: service/web/.
      args:
        app: netping
        sha: "unknown"
        ver: "dev"
        date: "2020-06-07 16:00:00+02:00"
    ports:
      - "80:80"
  ping:
    build:
      context: service/ping/.
      args:
        ver: "dev"
        date: "2020-06-07 16:00:00+02:00"
    ports:
      - "5000:5000"
