version: '3.7'
services:
  web:
    build:
      context: service/web/.
      args:
        app: netping
        sha: ${sha}
        ver: ${ver}
        date: ${date}
        min:
    ports:
      - "80:80"
  ping:
    build:
      context: service/ping/.
      args:
        sha: ${sha}
        ver: ${ver}
        date: ${date}
    ports:
      - "5000:5000"
  dns:
    build:
      context: service/dns/.
      args:
        sha: ${sha}
        ver: ${ver}
        date: ${date}
    ports:
      - "5001:5000"
