apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ service }}
  labels:
    app: {{ service }}
spec:
  selector:
    matchLabels:
      app: {{ service }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ service }}
    spec:
      containers:
      - name: {{ service }}
        image: {{ registry }}/{{ actor }}/{{ app }}/{{ service }}:{{ ver }}
        ports:
        - containerPort: 80
