apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ service }}
  labels:
    app: {{ service }}
spec:
  tls:
  - hosts:
    - {{ app }}.{{ domain }}
    secretName: tls
  rules:
    - host: {{ app }}.{{ domain }}
      http:
        paths:
        - path: /*
          backend:
            serviceName: {{ service }}
            servicePort: 80
