{% set host = app + '.' + domain %}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  tls:
  - hosts:
    - {{ host }}
    secretName: tls
  ingressClassName: nginx
  rules:
    - host: {{ host }}
      http:
        paths:
        - path: /
          backend:
            serviceName: web
            servicePort: 80
---
{% set api = 'api.' + host %}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  labels:
    app: backend
spec:
  tls:
  - hosts:
    - {{ api }}
    secretName: tls
  ingressClassName: nginx
  rules:
    - host: {{ api }}
      http:
        paths:
{% for service in [
  'whoami',
  'ping',
  'dns',
  'send'
  ]
%}
        - path: /{{ service }}/
          backend:
            serviceName: {{ service }}
            servicePort: 5000
{% endfor %}
