---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
spec:
  tls:
    - hosts:
        - {{ domain }}
      secretName: tls
  ingressClassName: nginx
  rules:
    - host: {{ domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80



{% set host = app + '.' + domain %}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  tls:
  - hosts:
    - {{ host }}
    secretName: tls
  ingressClassName: nginx
  rules:
    - host: {{ host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: web
              port:
                number: 80
---
{% set api = 'api.' + host %}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  labels:
    app: backend
spec:
  tls:
  - hosts:
    - {{ api }}
    secretName: tls
  ingressClassName: nginx
  rules:
    - host: {{ api }}
      http:
        paths:
{% for service in [
  'whoami',
  'ping',
  'dns',
  'send'
  ]
%}
        - path: /{{ service }}/
          pathType: Prefix
          backend:
            service:
              name: {{ service }}
              port:
                number: 5000
{% endfor %}
