name: CI

on:
  push:
    branches:
    - master

env:
  app: netping
  image: frontend
  registry: docker.pkg.github.com

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build image
      run: |
        ver=$(git rev-parse --short HEAD)
        tag=$registry/${{ github.repository }}/$image:$ver
        cd $image
        docker build . --tag $tag --build-arg app=$app --build-arg ver=$ver
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login $registry -u ${{ github.actor }} --password-stdin
        docker push $tag

    - name: deploy
      env:
        K8S_SERVER: ${{ secrets.K8S_SERVER }}
        K8S_USER: ${{ secrets.K8S_USER }}
        K8S_PASS: ${{ secrets.K8S_PASS }}
      run: |
        kubectl config set-cluster kube --server=https://$K8S_SERVER --insecure-skip-tls-verify=true
        kubectl config set-credentials CI --username=$K8S_USER --password=$K8S_PASS
        kubectl config set-context kube --cluster=kube --user=CI --namespace=$app
        kubectl config use-context kube
        kubectl version
