name: CI

on:
  push:
    branches:
    - master

env:
  app: netping
  service: frontend
  registry: docker.pkg.github.com
  actor: ${{ github.actor }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set env
      run: |
        ver=$(git rev-parse --short HEAD)
        echo "::set-env name=ver::$ver"
        echo "::set-env name=tag::$registry/${{ github.repository }}/$service:$ver"

    - name: build image
      run: |
        cd $service
        docker build . --tag $tag --build-arg app=$app --build-arg ver=$ver
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login $registry -u $actor --password-stdin
        docker push $tag

    - name: tf init
      env:
        be_token: ${{ secrets.be_token }}
        TF_VAR_do_token: ${{ secrets.do_token }}
        TF_VAR_letsencrypt_url: https://acme-staging-v02.api.letsencrypt.org/directory
        #TF_VAR_letsencrypt_url: https://acme-v02.api.letsencrypt.org/directory
        TF_VAR_domain: org
        TF_VAR_app: $app
      run: |
        cd terraform
        ./init.sh

    - name: deploy
      env:
        K8S_SERVER: ${{ secrets.K8S_SERVER }}
        K8S_USER: ${{ secrets.K8S_USER }}
        K8S_PASS: ${{ secrets.K8S_PASS }}
      run: |
        cd manifest
        ./kubeconfig.sh
        ./deploy.sh
