name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build image
      env:
        registry: malferov
      run: |
        ver=$(git rev-parse --short HEAD)
        tag=$registry/${{ github.repository }}:$ver
        docker build . --tag $tag --build-arg app=${{ github.repository }} --build-arg ver=$ver
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        docker push $tag
