name: CI

on:
  push:
    branches:
    - master
    - feature/*

env:
  app: netping
  domain: org
  TF_VAR_app: netping
  TF_VAR_domain: org
  registry: docker.pkg.github.com
  actor: ${{ github.actor }}

  TF_INPUT: 0
  TF_IN_AUTOMATION: 1
  TF_VAR_do_token: ${{ secrets.do_token }}
  TF_VAR_letsencrypt_url: https://acme-v02.api.letsencrypt.org/directory
  TF_VAR_email: ${{ secrets.email }}

  K8S_SERVER: ${{ secrets.K8S_SERVER }}
  K8S_CAD: ${{ secrets.K8S_CAD }}
  K8S_CSD: ${{ secrets.K8S_CSD }}
  K8S_CKD: ${{ secrets.K8S_CKD }}

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: deps
      run: sudo pip install jinja2-cli

    - name: tls and dns
      env:
        be_token: ${{ secrets.be_token }}
      run: |
        cd terraform
        ./init.sh
        terraform apply -auto-approve -var="ip=${{ secrets.K8S_SERVER }}"
        echo "::set-env name=crt::$(terraform output crt)"
        echo "::set-env name=key::$(terraform output key)"

    - name: ingress
      run: |
        echo "::add-mask::$crt"
        echo "::add-mask::$key"
        cd manifest
        ./kubeconfig.sh
        kubectl version
        #./ingress.sh

  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
        - web
        - ping
    steps:
    - uses: actions/checkout@v2

    - name: set env
      run: |
        ver=$(git rev-parse --short HEAD)
        echo "::set-env name=ver::$ver"
        echo "::set-env name=tag::$registry/${{ github.repository }}/${{ matrix.service }}:$ver"
        sudo pip install jinja2-cli

    - name: build image
      run: |
        cd ${{ matrix.service }}
        docker build . --tag $tag \
          --build-arg app=$app \
          --build-arg ver=$ver \
          --build-arg date="$(date --rfc-3339=seconds)"
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login $registry -u $actor --password-stdin
        docker push $tag

    - name: deploy service
      run: |
        cd manifest
        ./kubeconfig.sh
        ./service.sh ${{ matrix.service }}
