name: CI

on:
  push:
    branches:
    - master

env:
  app: netping
  service: frontend
  registry: docker.pkg.github.com
  actor: ${{ github.actor }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set env
      run: |
        echo "::set-env name=ver::$(git rev-parse --short HEAD)"
        echo "::set-env name=tag::$registry/${{ github.repository }}/$service:$ver"

    - name: build image
      run: |
        #ver=$(git rev-parse --short HEAD)
        #tag=$registry/${{ github.repository }}/$service:$ver
        echo ver=$ver tag=$tag
        cd $service
        docker build . --tag $tag --build-arg app=$app --build-arg ver=$ver
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login $registry -u $actor --password-stdin
        docker push $tag

    - name: deploy
      env:
        K8S_SERVER: ${{ secrets.K8S_SERVER }}
        K8S_USER: ${{ secrets.K8S_USER }}
        K8S_PASS: ${{ secrets.K8S_PASS }}
      run: |
        #cd manifest
        #./kubeconfig.sh
        #./deploy.sh
