name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build image
      env:
        registry: docker.pkg.github.com
      run: |
        ver=$(git rev-parse --short HEAD)
        echo "github.repository = ${{ github.repository }}"
        echo "github.actor = ${{ github.actor }}"
        tag=$registry/${{ github.repository }}:$ver
        docker build . --tag $tag --build-arg app=${{ github.repository }} --build-arg ver=$ver
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login  -u ${{ github.actor }} --password-stdin
        docker push $tag
