name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build image
      env:
        registry: malferov
        app: netping
      run: |
        ver=$(git rev-parse --short HEAD)
        tag=$registry/$app:$ver
        docker build . --tag $tag --build-arg app=$app --build-arg ver=$ver
        #docker push $tag
